name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 8 * * 1'   # Runs every Monday at 8 AM UTC
  workflow_dispatch:       # Allows manual run if needed

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping your site
        run: |
          echo "Pinging your Supabase or site to keep it alive..."
          curl -s -o /dev/null https://consultancy-durb.vercel.app/
